environment:
  ELECTRON_RUN_AS_NODE: 1
  VSCODE_BUILD_VERBOSE: true

install:
  - ps: Install-Product node 9.3.0 x64

build_script:
  - npm install
  - npm run vscode:prepublish

test_script:
  - npm test
